apiVersion: v1
baseDomain: openshiftaws.com
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: r5.xlarge
  replicas: 2
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: m5.xlarge
      zones:
      - us-east-1a
  replicas: 3
metadata:
  creationTimestamp: null
  name: ly-demo
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
#additionalTrustBundle: |
#  -----BEGIN CERTIFICATE-----
#  xxxyyyyzzzz
#  -----END CERTIFICATE-----
# optional
#sshKey: |
#  <SSH_PUB_KEY>
pullSecret: '<PULL_SECRET>'
