apiVersion: v1
baseDomain: openshiftaws.com
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: r5.xlarge
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: m5.xlarge
      zones:
      - us-east-1a
  replicas: 3
metadata:
  creationTimestamp: null
  name: ly-demo
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
#additionalTrustBundle: |
#  -----BEGIN CERTIFICATE-----
#  xxxyyyyzzzz
#  -----END CERTIFICATE-----
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2FsbHlyZWRoYXRjb20xb3Rha2lwbHh2b212cXJ0aHhvODc0MXZubmI6UUdFNDlHM0hNOTk3WldUNjhONUFDV0Q4SU5PU1NCOUw1QkM0TkpZQlVDTVRRNDUwTkIzTldYNVA2Q0RDVFU2UQ==","email":"ally@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2FsbHlyZWRoYXRjb20xb3Rha2lwbHh2b212cXJ0aHhvODc0MXZubmI6UUdFNDlHM0hNOTk3WldUNjhONUFDV0Q4SU5PU1NCOUw1QkM0TkpZQlVDTVRRNDUwTkIzTldYNVA2Q0RDVFU2UQ==","email":"ally@redhat.com"},"registry.connect.redhat.com":{"auth":"NTI3NTY5Mzd8dWhjLTFPdEFLaXBsWFZvTXZRUnRoeG84NzQxVk5OQjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBNalEyWTJNellqTXlObUUwWlRSaE9EWXhaVFkzTWpJd00yUXpaV1U1TUNKOS5vYVUwV1ppMnY4WnNwemwzTXZtbjZRUXNrS0kzMUZRbjNwWjV4VnVCYUY1ZUJrcl9JYjA1OTlOOW5Zd2h6RFZ6dVR2WlZXLUhrTFdMQm5XM1l0SXA3akNZVS1RMXBrMWI1S1lkZ1Q5cDhPM2lIMndrYTZqQWdGb0pNaU9UbHh2NzJhbXlqRnQ3YmJoeEg1eFNYeUkxWVRZRFc4UEtjZk5LQjc1ZEFVdXY0U2p1dmc4MmZfVWFYN3NDU2RsLTE4YmhDMk8xcGgtLURwTFJFbTVUczc5UjNmdEpjeWV2M3RYaXk2eFFyTFF5ZHBLTFJLd2hGUFk5Rlh3S3BhVS1oN05JNU5MYXRqM0dnZ2ZsVHdVLWwtODVFTGg1ak9NUE5XOTZOU0piM0UySzRhMEFFTnRSZ3IwVHVzQ3RUN01PMU14ek1FOEkyTXZBT29aSGp2UWZvNzVwenY0c3dJVnZaWU5xUGxudGlLWnVYTHVNTjBEQmRmaTdwRUR1NDVNaUVuNkk0SGtNRlB0RThkazYxR3BMMWYtaWh2Z0hDZGhWUEZiR25fcnpCQk4tM0tNcHBUdG1BcmxaQlJEOGdGRjJCTEl1b0wtb2FFUlQ2M3J1ckVieTM2dk1rQ0JBa3BLV3g5SE93dG1NWldKN3M4MThvbjBYcVZxazY0UUoxZlVhVm14RkgwNXFZRUtSQk51d1F2c2JFZnVQcm9wemFaekM1WDM2NktrZVlVVWlaV0pNa19EMmtOaU5mem12M0Z2V21sM0hSX1ByWThsVDF4bjZzUEFDMy12SWMyZnplRHo3RE1ZLU9BREVVNUFyQnhfcnpvcDhYWUQ1MXBTRFl0WmY4Vk9QY1g0RmdNWVhYQzJwQVZIV1JYdlNhc201a2M1OWViX1VSVXp0VmxmbTFPRQ==","email":"ally@redhat.com"},"registry.redhat.io":{"auth":"NTI3NTY5Mzd8dWhjLTFPdEFLaXBsWFZvTXZRUnRoeG84NzQxVk5OQjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBNalEyWTJNellqTXlObUUwWlRSaE9EWXhaVFkzTWpJd00yUXpaV1U1TUNKOS5vYVUwV1ppMnY4WnNwemwzTXZtbjZRUXNrS0kzMUZRbjNwWjV4VnVCYUY1ZUJrcl9JYjA1OTlOOW5Zd2h6RFZ6dVR2WlZXLUhrTFdMQm5XM1l0SXA3akNZVS1RMXBrMWI1S1lkZ1Q5cDhPM2lIMndrYTZqQWdGb0pNaU9UbHh2NzJhbXlqRnQ3YmJoeEg1eFNYeUkxWVRZRFc4UEtjZk5LQjc1ZEFVdXY0U2p1dmc4MmZfVWFYN3NDU2RsLTE4YmhDMk8xcGgtLURwTFJFbTVUczc5UjNmdEpjeWV2M3RYaXk2eFFyTFF5ZHBLTFJLd2hGUFk5Rlh3S3BhVS1oN05JNU5MYXRqM0dnZ2ZsVHdVLWwtODVFTGg1ak9NUE5XOTZOU0piM0UySzRhMEFFTnRSZ3IwVHVzQ3RUN01PMU14ek1FOEkyTXZBT29aSGp2UWZvNzVwenY0c3dJVnZaWU5xUGxudGlLWnVYTHVNTjBEQmRmaTdwRUR1NDVNaUVuNkk0SGtNRlB0RThkazYxR3BMMWYtaWh2Z0hDZGhWUEZiR25fcnpCQk4tM0tNcHBUdG1BcmxaQlJEOGdGRjJCTEl1b0wtb2FFUlQ2M3J1ckVieTM2dk1rQ0JBa3BLV3g5SE93dG1NWldKN3M4MThvbjBYcVZxazY0UUoxZlVhVm14RkgwNXFZRUtSQk51d1F2c2JFZnVQcm9wemFaekM1WDM2NktrZVlVVWlaV0pNa19EMmtOaU5mem12M0Z2V21sM0hSX1ByWThsVDF4bjZzUEFDMy12SWMyZnplRHo3RE1ZLU9BREVVNUFyQnhfcnpvcDhYWUQ1MXBTRFl0WmY4Vk9QY1g0RmdNWVhYQzJwQVZIV1JYdlNhc201a2M1OWViX1VSVXp0VmxmbTFPRQ==","email":"ally@redhat.com"}}}'
#sshKey: |
  #ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNtGMycVRS6hzo7ytpvvnO43dryU/jPZoXbceVlflxyGVXQAXnrBKxoBLCqpdW5ygt9oWFdGe4YbYR+ZoqqQRx8OMM7XcGUGKU2vNMMyRpVrAQAeIeinERdYQmTX8P8T15L2Sp9XPIQqb/ZqrtgeYznZzrH9nEonV65nKVKYJ2q4nQG6pZK+VoVTjwXqvkgMvBtSO6LxE4klJq9VTEVlVD7Pxw2p9Meor+nFu9bbuCeMxzZlhePV+UQKxl6m/ZqvWZyA2dgPbtm5f0FOKtMoU04Z4HR6zRqJqeGu4is515NEwu0ubOUARp2zCWxxnxbcIfJD3LjnhlkZ2IQJRTyVD5 alexly@MacBook-Pro
